# Generated by Django 5.1.6 on 2025-05-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0004_remove_aviso_professor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("aviso", models.CharField(max_length=50000)),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=8)),
                ("numero", models.IntegerField()),
                (
                    "ano",
                    models.CharField(
                        choices=[
                            ("1° ano", "1° ano"),
                            ("2° ano", "2° ano"),
                            ("3° ano", "3° ano"),
                            ("4° ano", "4° ano"),
                            ("5° ano", "5° ano"),
                            ("6° ano", "6° ano"),
                            ("7° ano", "7° ano"),
                            ("8° ano", "8° ano"),
                            ("9° ano", "9° ano"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "turma",
                    models.CharField(
                        choices=[
                            ("Turma A", "Turma A"),
                            ("Turma B", "Turma B"),
                            ("Turma C", "Turma C"),
                            ("Turma D", "Turma D"),
                            ("Turma E", "Turma E"),
                            ("Turma F", "Turma F"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.aluno"
                    ),
                ),
            ],
        ),
    ]
