# Generated by Django 5.1.6 on 2025-02-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('senha', models.CharField(default='passworddefault', max_length=200)),
                ('telefone', models.CharField(default='000000000', max_length=14)),
                ('ano', models.CharField(choices=[('1° ano', '1° ano'), ('2° ano', '2° ano'), ('3° ano', '3° ano'), ('4° ano', '4° ano'), ('5° ano', '5° ano'), ('6° ano', '6° ano'), ('7° ano', '7° ano'), ('8° ano', '8° ano'), ('9° ano', '9° ano')], max_length=250)),
                ('turma', models.CharField(choices=[('Turma A', 'Turma A'), ('Turma B', 'Turma B'), ('Turma C', 'Turma C'), ('Turma D', 'Turma D'), ('Turma E', 'Turma E'), ('Turma F', 'Turma F')], max_length=250)),
                ('rec', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('nota1', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('nota2', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('nota3', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('nota4', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('observacao', models.TextField(default='Escreva alguma observação', max_length=12000)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Trabalho em dupla', 'Trabalho em dupla'), ('Trabalho com 4 comp.', 'Trabalho com 4 comp.'), ('Prova', 'Prova'), ('Trabalho individual', 'Trabalho individual')], max_length=250)),
                ('observacao', models.TextField(default='Descreva sobre o desempenho dos componentes', max_length=12000)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avaliacao')),
            ],
            options={
                'unique_together': {('aluno', 'avaliacao')},
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='alunos',
            field=models.ManyToManyField(through='app.NotaAvaliacao', to='app.aluno'),
        ),
    ]
