# Generated by Django 5.1.6 on 2025-04-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.IntegerField(default=0, unique=True)),
                ("nome", models.CharField(max_length=250)),
                ("telefone", models.CharField(default="000000000", max_length=14)),
                (
                    "rec",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "nota1",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "nota2",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "nota3",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "nota4",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "turma",
                    models.CharField(
                        choices=[
                            ("Turma A", "Turma A"),
                            ("Turma B", "Turma B"),
                            ("Turma C", "Turma C"),
                            ("Turma D", "Turma D"),
                            ("Turma E", "Turma E"),
                            ("Turma F", "Turma F"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        choices=[
                            ("1° ano", "1° ano"),
                            ("2° ano", "2° ano"),
                            ("3° ano", "3° ano"),
                            ("4° ano", "4° ano"),
                            ("5° ano", "5° ano"),
                            ("6° ano", "6° ano"),
                            ("7° ano", "7° ano"),
                            ("8° ano", "8° ano"),
                            ("9° ano", "9° ano"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField(default="cwoss")),
                ("nome", models.CharField(max_length=250)),
                (
                    "turma",
                    models.CharField(
                        choices=[
                            ("Turma A", "Turma A"),
                            ("Turma B", "Turma B"),
                            ("Turma C", "Turma C"),
                            ("Turma D", "Turma D"),
                            ("Turma E", "Turma E"),
                            ("Turma F", "Turma F"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        choices=[
                            ("1° ano", "1° ano"),
                            ("2° ano", "2° ano"),
                            ("3° ano", "3° ano"),
                            ("4° ano", "4° ano"),
                            ("5° ano", "5° ano"),
                            ("6° ano", "6° ano"),
                            ("7° ano", "7° ano"),
                            ("8° ano", "8° ano"),
                            ("9° ano", "9° ano"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="app.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("aviso", models.CharField(max_length=50000)),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.professor"
                    ),
                ),
            ],
        ),
    ]
