# Generated by Django 5.1.6 on 2025-03-05 20:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("aviso", models.CharField(max_length=50000)),
                (
                    "data",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 3, 5, 20, 34, 43, 848167, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.aluno"
                    ),
                ),
            ],
        ),
    ]
