# Generated by Django 5.1.6 on 2025-02-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(choices=[('1° ano', '1° ano'), ('2° ano', '2° ano'), ('3° ano', '3° ano'), ('4° ano', '4° ano'), ('5° ano', '5° ano'), ('6° ano', '6° ano'), ('7° ano', '7° ano'), ('8° ano', '8° ano'), ('9° ano', '9° ano')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('Turma A', 'Turma A'), ('Turma B', 'Turma B'), ('Turma C', 'Turma C'), ('Turma D', 'Turma D'), ('Turma E', 'Turma E'), ('Turma F', 'Turma F')], max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ano'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=25)),
                ('turma', models.ManyToManyField(to='app.aluno')),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
