# Generated by Django 5.1.6 on 2025-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_professor_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
