# Generated by Django 5.1.6 on 2025-03-05 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_aviso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviso",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 3, 5, 20, 37, 5, 195190, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
