# Generated by Django 5.1.6 on 2025-02-18 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_ano_turma_alter_aluno_ano_professor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anotacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=datetime.date(2025, 2, 18))),
                (
                    "anotacao",
                    models.CharField(default="Escreva algo Hoje!", max_length=10000),
                ),
                ("tipo", models.CharField(default="Sem tipo definido", max_length=200)),
                ("importancia", models.IntegerField(default=1, max_length=5)),
            ],
        ),
    ]
