# Generated by Django 5.1.6 on 2025-03-05 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_aviso_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aviso",
            name="aluno",
        ),
        migrations.AlterField(
            model_name="aviso",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 3, 5, 20, 38, 33, 89953, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
