# Generated by Django 5.1.6 on 2025-02-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_anotacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacoes",
            name="importancia",
            field=models.IntegerField(default=1),
        ),
    ]
