# Generated by Django 5.1.6 on 2025-05-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_aviso_professor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aviso",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="turma",
        ),
    ]
