# Generated by Django 5.1.6 on 2025-02-18 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_anotacoes_importancia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacoes",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 18, 18, 0, 37, 296469, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
