# Generated by Django 5.1.6 on 2025-02-18 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_anotacoes_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacoes",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 18, 18, 1, 50, 363864, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
