# Generated by Django 5.1.6 on 2025-02-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_anotacoes_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacoes",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 22, 17, 19, 30, 554159, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
