# Generated by Django 5.1.6 on 2025-02-22 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_anotacoes_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="ano",
            field=models.CharField(
                choices=[
                    ("1° ano", "1° ano"),
                    ("2° ano", "2° ano"),
                    ("3° ano", "3° ano"),
                    ("4° ano", "4° ano"),
                    ("5° ano", "5° ano"),
                    ("6° ano", "6° ano"),
                    ("7° ano", "7° ano"),
                    ("8° ano", "8° ano"),
                    ("9° ano", "9° ano"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="anotacoes",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 22, 17, 29, 18, 469724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
