# Generated by Django 5.1.6 on 2025-02-22 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_aluno_ano_alter_anotacoes_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ano",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="turma",
            field=models.CharField(
                choices=[
                    ("Turma A", "Turma A"),
                    ("Turma B", "Turma B"),
                    ("Turma C", "Turma C"),
                    ("Turma D", "Turma D"),
                    ("Turma E", "Turma E"),
                    ("Turma F", "Turma F"),
                ],
                max_length=250,
            ),
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="senha",
        ),
        migrations.AddField(
            model_name="aluno",
            name="matricula",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="anotacoes",
            name="data",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 22, 17, 34, 7, 413258, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="Turma",
        ),
    ]
