# Generated by Django 5.1.6 on 2025-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_delete_ano_alter_aluno_turma_remove_aluno_senha_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Anotacoes",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
