# Generated by Django 5.1.6 on 2025-03-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_delete_anotacoes_alter_aluno_matricula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("presente", models.BooleanField(default=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.aluno"
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "data")},
            },
        ),
    ]
